# üß© Reto 3 ‚Äì Ox√≠geno disuelto
**Objetivo:** evaluar riesgo ecol√≥gico seg√∫n ox√≠geno disuelto.

**Datos:** `../data/muestras_calidad_agua.csv`

### Pasos
1. Carga el CSV en `df`.
2. Extrae `sitio` y `oxigeno`.
3. Crea `nivel_oxigeno` (bajo/medio/alto).
4. Crea `riesgo_biologico` (‚ö† si ox√≠geno < 5).
5. Filtra y exporta `resultado_oxigeno.csv`.

> **Reto adicional:** porcentaje de sitios con riesgo.

In [27]:
import pandas as pd

# Paso 1: Cargar el archivo CSV en df:
df = pd.read_csv("muestras_calidad_agua.csv")


df

                           sitio   pH  oxigeno  temperatura
0                 R√≠o Subachoque  7.2      7.8         18.5
1    Quebrada Honda (Facatativ√°)  6.3      6.2         19.4
2           R√≠o Botello (Madrid)  6.8      5.9         22.7
3   Afluente San Jos√© (El Rosal)  7.9      8.3         20.1
4                    R√≠o Villeta  8.7      6.1         28.3
5  Quebrada Cune (San Francisco)  6.0      4.5         25.2
6            R√≠o Tobia (Nocaima)  7.4      5.2         26.9
7       Quebrada Negra (La Vega)  7.6      7.0         24.4
8          R√≠o Baham√≥n (Sasaima)  8.1      6.7         27.6
9        R√≠o Guayuriba (La Mesa)  5.9      4.8         30.5

In [28]:
# Paso 2: Seleccionar columnas necesarias
df_oxigeno = df[["sitio", "oxigeno"]].copy()
df_oxigeno

                           sitio  oxigeno
0                 R√≠o Subachoque      7.8
1    Quebrada Honda (Facatativ√°)      6.2
2           R√≠o Botello (Madrid)      5.9
3   Afluente San Jos√© (El Rosal)      8.3
4                    R√≠o Villeta      6.1
5  Quebrada Cune (San Francisco)      4.5
6            R√≠o Tobia (Nocaima)      5.2
7       Quebrada Negra (La Vega)      7.0
8          R√≠o Baham√≥n (Sasaima)      6.7
9        R√≠o Guayuriba (La Mesa)      4.8

In [31]:
# Paso 3 Clasificaci√≥n del nivel de ox√≠geno
def nivel_oxigeno(valor):
  if valor <4:
    return "Bajo"
  elif valor <8:
    return "Medio"
  else:
    return "Alto"
      
df_oxigeno["nivel_oxigeno"]= df_oxigeno["oxigeno"].apply(nivel_oxigeno)
df_oxigeno

                           sitio  oxigeno nivel_oxigeno riesgo_biologico
0                 R√≠o Subachoque      7.8         Medio       sin riesgo
1    Quebrada Honda (Facatativ√°)      6.2         Medio       sin riesgo
2           R√≠o Botello (Madrid)      5.9         Medio       sin riesgo
3   Afluente San Jos√© (El Rosal)      8.3          Alto       sin riesgo
4                    R√≠o Villeta      6.1         Medio       sin riesgo
5  Quebrada Cune (San Francisco)      4.5         Medio           riesgo
6            R√≠o Tobia (Nocaima)      5.2         Medio       sin riesgo
7       Quebrada Negra (La Vega)      7.0         Medio       sin riesgo
8          R√≠o Baham√≥n (Sasaima)      6.7         Medio       sin riesgo
9        R√≠o Guayuriba (La Mesa)      4.8         Medio           riesgo

In [32]:
# Paso 4 Riesgo Biol√≥gico
def riesgo_biologico (valor):
    if valor <5:
        return "riesgo"
    else:
        return "sin riesgo"
df_oxigeno["riesgo_biologico"]=df_oxigeno["oxigeno"].apply(riesgo_biologico)
df_oxigeno

                           sitio  oxigeno nivel_oxigeno riesgo_biologico
0                 R√≠o Subachoque      7.8         Medio       sin riesgo
1    Quebrada Honda (Facatativ√°)      6.2         Medio       sin riesgo
2           R√≠o Botello (Madrid)      5.9         Medio       sin riesgo
3   Afluente San Jos√© (El Rosal)      8.3          Alto       sin riesgo
4                    R√≠o Villeta      6.1         Medio       sin riesgo
5  Quebrada Cune (San Francisco)      4.5         Medio           riesgo
6            R√≠o Tobia (Nocaima)      5.2         Medio       sin riesgo
7       Quebrada Negra (La Vega)      7.0         Medio       sin riesgo
8          R√≠o Baham√≥n (Sasaima)      6.7         Medio       sin riesgo
9        R√≠o Guayuriba (La Mesa)      4.8         Medio           riesgo

In [33]:
# Reto adicional: Resumen y porcentaje de sitios con riesgo
print("Resumen por nivel:")
print(df_oxigeno["nivel_oxigeno"].value_counts())
print("")

total=len(df_oxigeno)
riesgo=(df_oxigeno["riesgo_biologico"]=="riesgo").sum()
porcentaje=(riesgo/total)*100

print("total sitios:",total)
print("sitios en riesgo:",riesgo)
print("porcentaje de sitios con riesgo:",(porcentaje,1),"%")

Resumen por nivel:
nivel_oxigeno
Medio    9
Alto     1
Name: count, dtype: int64

total sitios: 10
sitios en riesgo: 2
porcentaje de sitios con riesgo: (20.0, 1) %

In [34]:
# Paso 5 Exportar resultados
df_oxigeno.to_csv("resultado_oxigeno.csv",index=False)
print("Archivo'resultado_oxigeno.csv' guardado correctamente")

Archivo'resultado_oxigeno.csv' guardado correctamente